autobrr/omegabrr

- .gitignore
- README.md
- config.yml
- internal/domain/config.go
- internal/http/processor.go
- internal/processor/radarr.go
- internal/processor/service.go
- internal/processor/sonarr.go
- internal/processor/tags.go
- internal/processor/tags_test.go
Add the option to include or exclude titles with certain tags.
> feat(arr): include exclude tags

- internal/processor/title.go
Remove `!` from titles like `American Dad!`.
> feat(titles): clean exclamation mark

- README.md
- internal/processor/radarr.go
- internal/processor/service.go
- internal/processor/sonarr.go
- pkg/autobrr/client.go
Support basic auth for autobrr.
> feat(autobrr): support basic auth

- internal/domain/config.go
- internal/processor/lidarr.go
- internal/processor/readarr.go
- internal/processor/service.go
Tested locally and it fetches monitored titles from both.
I did not get tags to work for any of them so those parts are commented out in case anyone else makes it work.
> feat(arr): add readarr and lidarr support

- README.md
Thanks again for adding these features!
> docs: add lidarr and readarr to example config

- .github/workflows/build.yaml
Update goreleaser action version due to github issues https://github.com/goreleaser/goreleaser-action/issues/389
> build: update goreleaser action version

- cmd/omegabrr/main.go
- internal/domain/config.go
Write the config with commented out defaults for the user to update.
Fixes #11
> fix(config): change default

- README.md
- distrib/systemd/omegabrr@.service
Add systemd unit examples to run on linux systems.
Resolves #10
> docs: add systemd unit example

- .github/workflows/build.yaml
> build: correct release flag arg

- README.md
changed wrong autobrr occurences to omegabrr.
> fix(readme): autobrr occurences to omegabrr

- internal/domain/config.go
> fix(config): fixed typo in configTemplate

- internal/domain/config.go
As troubleshooted here: https://discord.com/channels/881212911849209957/1074507615909986344/1074570936424087572
The tabs make the config invalid. Tested myself and confirmed.
> fix(config): removed tabs in config

- internal/domain/config.go
So apparently the config generated still fails on the autobrr basic auth part, as well as Lidarr/Readarr.
I have checked that this validates 20 times with yamllint.com, but please someone look it over, because it's starting to get really frustrating and embarassing that I cannot get this right.
> fix(config) fixed bad indentations

- go.mod
- go.sum
- internal/processor/title.go
- internal/processor/title_test.go
> enhancement(parsing): improved parsing of titles and added tests

- internal/processor/title.go
- internal/processor/title_test.go
Added missing option for apostrophe and region code in one title.
> fix(parsing): added one missing option to parsing

- README.md
fix version typos in README.md
> fix version typos in README.md

- distrib/systemd/omegabrr@.service
Changes ExecStart to be valid.
> fix(distrib): systemd add `run` to run as a daemon

- cmd/omegabrr/main.go
> feat: `omegabrr version` show latest release

- internal/domain/config.go
Exits program if an arr/list is set without "filters", "host" or "url".
That way it will exit if user mixes url/host between arr/lists, or if they use "filter" instead of "filters".
> feat(config): validate config

- README.md
Update overview to mention lists
> docs: update overview text

- internal/processor/metacritic.go
- pkg/autobrr/client.go
add both artists and albums to the filter, resulting in more accurate matches
> feat(lists): include artists for metacritic lists

- cmd/omegabrr/main.go
Basically the same as autobrr/autobrr#1248
Removed SIGKILL.
> refactor: streamline shutdown signal handling

- Dockerfile
- Makefile
- cmd/omegabrr/main.go
- internal/buildinfo/buildinfo.go
- internal/processor/client.go
- internal/processor/mdblist.go
- internal/processor/metacritic.go
- internal/processor/plaintext.go
- internal/processor/trakt.go
- pkg/autobrr/client.go
Add User-Agent for HTTP calls.
> feat: add useragent for requests

- .github/workflows/build.yaml
- Dockerfile.ci
Update workflows to build docker and all actions.
> build: update workflows

- .gitignore
- README.md
- internal/domain/config.go
- internal/processor/service.go
- internal/processor/steam.go
- internal/processor/title.go
- internal/processor/title_test.go
```yaml
lists:
- name: New Games
type: steam
url: https://store.steampowered.com/wishlist/id/USERNAME/wishlistdata
filters:
- 1 # Change me
```
> feat(lists): steam wishlist

- pkg/autobrr/client.go
Fixes an issue where having an end slash in the config for autobrr host would lead to `405 Method not allowed` errors with all requests to autobrr.
> fix(autobrr): host url with multiple slash

- README.md
- internal/domain/config.go
- internal/processor/radarr.go
- internal/processor/service.go
- internal/processor/service_test.go
- internal/processor/sonarr.go
> feat(arrs): add support for including unmonitored titles
